### ISSUE TITLE
make sure your bosh-dns links are actually returning bosh-dns values via features

### ISSUE THREAD

**Issue by aegershman** [aegershman/yugabyte-boshrelease#49]
https://bosh.io/docs/manifest-v2/#features

you should test at least having the following in the bosh deployment manifest:

```
features:
  use_dns_addresses: true
```

but these are all fun:

```yml
features:
  use_dns_addresses: true
  randomize_az_placement: true
  use_short_dns_addresses: true
```
