### ISSUE TITLE
Testing YEDIS with spring music appears to have cooperated

### ISSUE THREAD

**Issue by aegershman** [aegershman/yugabyte-boshrelease#95]
using spring-music with the following manifest.yml:

```yml
  - name: spring-music
    instances: 1
    memory: 1G
    disk_quota: 1G
    path: spring-music/build/libs/spring-music-1.0.jar
    buildpacks:
      - java_buildpack_offline
    random-route: true
    health-check-type: process
    env:
      SPRING_PROFILES_ACTIVE: redis
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    services:
      - yedis
```

where `yedis` is a user-provided service which looks like this:

```sh
  cf cups yedis -p '{"uri":"q-s0.tserver.services-network.yugabyte.bosh:6379"}'
```
